//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fase2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Ativos = new HashSet<Ativo>();
            this.EquipaFuncs = new HashSet<EquipaFunc>();
            this.Competencias = new HashSet<Competencia>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public int cc { get; set; }
        public int nif { get; set; }
        public System.DateTime dtNasc { get; set; }
        public string endereco { get; set; }
        public string email { get; set; }
        public string ntelefone { get; set; }
        public string profissao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ativo> Ativos { get; set; }
        public virtual EquipaFunc EquipaFunc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipaFunc> EquipaFuncs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competencia> Competencias { get; set; }
    }
}
