//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fase2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_ResumoIntervencoes
    {
        public int IdIntervencao { get; set; }
        public string descIntervencao { get; set; }
        public string estadoIntervencao { get; set; }
        public System.DateTime dtInIntervencao { get; set; }
        public Nullable<System.DateTime> dtFimIntervencao { get; set; }
        public Nullable<decimal> valorIntervencao { get; set; }
        public string nomeAtivo { get; set; }
        public System.DateTime dtAquisicaoAtivo { get; set; }
        public string marcaAtivo { get; set; }
        public string modeloAtivo { get; set; }
        public string locAtivo { get; set; }
        public Nullable<decimal> valorAtivo { get; set; }
    }
}
