//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipaIntervencao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipaIntervencao()
        {
            this.HistAlteracaoEqIntervs = new HashSet<HistAlteracaoEqInterv>();
        }
    
        public int idIntervencao { get; set; }
        public Nullable<int> equipaId { get; set; }
    
        public virtual Equipa Equipa { get; set; }
        public virtual Intervencao Intervencao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistAlteracaoEqInterv> HistAlteracaoEqIntervs { get; set; }
    }
}
