//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistAlteracaoEqInterv
    {
        public int idIntervencao { get; set; }
        public Nullable<int> equipaId { get; set; }
        public System.DateTime dtAtualizacao { get; set; }
    
        public virtual EquipaIntervencao EquipaIntervencao { get; set; }
    }
}
