//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ativo()
        {
            this.Ativos1 = new HashSet<Ativo>();
            this.Historicoes = new HashSet<Historico>();
            this.Intervencaos = new HashSet<Intervencao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> valor { get; set; }
        public System.DateTime dtAquisicao { get; set; }
        public Nullable<bool> estado { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string localizacao { get; set; }
        public Nullable<int> parentId { get; set; }
        public int tipoId { get; set; }
        public int gestorId { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ativo> Ativos1 { get; set; }
        public virtual Ativo Ativo1 { get; set; }
        public virtual Tipos Tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico> Historicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervencao> Intervencaos { get; set; }
    }
}
