//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipa()
        {
            this.EquipaFuncs = new HashSet<EquipaFunc>();
            this.EquipaIntervencaos = new HashSet<EquipaIntervencao>();
        }
        
        public int id { get; set; }
        public string localizacao { get; set; }
        public Nullable<int> nFunc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipaFunc> EquipaFuncs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipaIntervencao> EquipaIntervencaos { get; set; }
    }
}
