//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervencao
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string estado { get; set; }
        public System.DateTime dtInicio { get; set; }
        public Nullable<System.DateTime> dtFim { get; set; }
        public Nullable<decimal> valor { get; set; }
        public int ativoId { get; set; }
    
        public virtual Ativo Ativo { get; set; }
        public virtual EquipaIntervencao EquipaIntervencao { get; set; }
        public virtual IntervencaoPeriodica IntervencaoPeriodica { get; set; }
    }
}
