//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fase2_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int idAtivo { get; set; }
        public System.DateTime dtAlteracao { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Ativo Ativo { get; set; }
    }
}
